version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "caramelo2"
    ports:
      - "2022:5432"
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf